---
# Max water: 2,5 m³/hour = ~41.66 liter / minute = ~0.7 liter / second
# -> 1.44 second per liter -> fastest time between pulses is 1.44 seconds

substitutions:
  devicename: "watermeter"

packages:
  berghmans.watermeter:
    url: https://github.com/Berghmans/watermeter
    ref: main
    file: watermeter.yaml
    refresh: 1d
