---
# AZ Delivery ESP32
# TCRT5000 sensor
# Wiring:
#   - TCRT5000 A0 <-> ESP32 PIN 33
#   - TCRT5000 D0 <-> ESP32 PIN 32
#   - TCRT5000 GND <-> ESP32 PIN GND
#   - TCRT5000 VCC <-> ESP32 PIN 3v3

substitutions:
  devicename: "watermeter"
  friendly_name: "Watermeter"
  ir_digital_pin: GPIO32 # connect digital output from IR sensor to PIN 32
  ir_analog_pin: GPIO33 # connect analog output from IR sensor to PIN 33
  pulse_filter: 750ms

esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}
  project:
    name: berghmans.watermeter
    version: "1.0"

esp32:
  board: nodemcu-32s

web_server:
  port: 80

time:
  - platform: homeassistant
    id: my_time

wifi:
  ap:
    ssid: ${devicename}

captive_portal:

logger:

ota:

external_components:
  - source:
      type: git
      url: https://github.com/Berghmans/watermeter
      ref: main
    components: [ pulse_meter ]
    refresh: 1s

sensor:
  - platform: pulse_meter
    id: pulse_meter_water
    pin: ${ir_digital_pin}
    unit_of_measurement: "L/min"
    icon: "mdi:water"
    name: "Water Flow Rate"
    internal_filter: ${pulse_filter}
    internal_filter_mode: PULSE
    accuracy_decimals: 3
    timeout: 30s
    total:
      name: "Water Usage"
      unit_of_measurement: "m³"
      icon: "mdi:water"
      device_class: water
      state_class: total_increasing
      accuracy_decimals: 3
      filters:
        - multiply: 0.001
  # Optional sensor for measuring the analog value of the IR sensor
  # - platform: adc
  #   pin: ${ir_analog_pin}
  #   name: "Infrared measurement"
  #   update_interval: 500ms

api:
  services:
    - service: set_pulse_total
      variables:
        new_pulse_total: float
      then:
        - pulse_meter.set_total_pulses:
            id: pulse_meter_water
            value: !lambda "return new_pulse_total * 1000.0;"
